main: com.gmail.fingrambbg.goodvibes.GoodVibes
name: GoodVibes
version: 1.15
api-version: 1.15
author: RoboEx
description: This bad boi gives you good vibes
commands:
   celebrate:
     description: celebrate others on the server.
     usage: /celebrate [player]
     permission: goodvibes.celebrate
     permission-message: You don't have permission
   encourage:
     description: encourage others on the server.
     usage: /encourage [player]
     permission: goodvibes.encourage
     permission-message: You don't have permission
   rcelebrate:
     description: randomly celebrate others on the server.
     usage: /rcelebrate
     permission: goodvibes.rcelebrate
     permission-message: You don't have permission